### ISSUE TITLE
Master branch doesn't compile.

### ISSUE THREAD

**Issue by stephaun** [ektor5/secocec#1]
The latest master (42a6eab3a7116183f690453079b888fc6882a747) does not compile. It throws an error:

seco-cec.c:556:9: error 'CEC_CAP_DEFAULTS' undeclared

compilation terminated etc etc....

**Comment by ektor5** [comment]
Hi @stephaun ,
You should use the latest kernel version (at least 4.14), where CEC_CAP_DEFAULTS is defined.
