### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by drc85** [ektor5/secocec#2]
sorry to aks here, but i dont get any further... and im kind of new to linux.
i have created the folder and the seco-cec.ko file.
but now i dont get any further...

when i use --> modprobe.cec 
nothing happens. its like just pressing enter in the bash...

when i type-->  insmod seco-cec.ko
it says  --> insmod: ERROR: could not load module seco-cec.ko: No such file or directory
if i use cd secocec and then insmod seco-cec.ko i get this errror
--> insmod: ERROR: could not insert module seco-cec.ko: Operation not permitted

what should i need to do? i really would like to use cec :D

also i tried to compile with 4.14.13 and it didnt workded.. i switchted to 4.14.0 and it worked... maybe you should point this out in the readme....

thanks alot for the great work

**Comment by drc85** [comment]
ok i think i got it ...
went back to kernel 4.14... i was on kernel 4.14.13....

> sudo modprobe -v cec
> this is what it said:
> insmod /lib/modules/4.14.13-041413-generic/kernel/drivers/media/rc/rc-core.ko
> insmod /lib/modules/4.14.13-041413-generic/kernel/drivers/media/cec/cec.ko

> then
> cd secocec

> and then
> sudo insmod seco-cec.ko
> after this nothing happens and it jumps back to input...

> at the end
> lsmod
> to see if it is mounted...

just need to make a autostart skript now...

also having problems getting any further... 
i installed apt install v4l-utils
but i cant do nothing... really cant wait till i can use the tv remote LOL
cec-ctl or any other input always gives me command not found...

**Comment by ektor5** [comment]
Hi there,
Please use the forum for help on configuring: https://udoo.org/forum
You can either compile the tools with: https://git.linuxtv.org/media_tree.git/tree

Thanks,
Ek5
