### ISSUE TITLE
Kernel dump in seco-cec module when using TV remote

### ISSUE THREAD

**Issue by ocurero** [ektor5/secocec#3]
Env:
- Hardware: SECO UDOO x86/UDOO x86, BIOS 1.04 05/11/2018
- Distribution: Opensuse Tumbleweed
- Linux kernel: 4.18.11-1
- Seco-cec module: commit 18f1598f2ccfa7c5336ce608053fd832c6b31900.

Steps to reproduce:

1. Enable HDMI-CEC for LG SimpLink remotes:
```
cec-ctl --phys-addr=1.0.0.0 \
        --playback \
        --custom-command=cmd=0x89,payload=0x02:0x05 \
        --deck-status=deck-info=0x01 \
        --menu-status=menu-state=0x00 \
        --custom-command=cmd=0x89,payload=0x05:0x01 \
        --report-power-status=pwr-state=0 -t0
```

2. Press any button in the remote.

Attached is the dmesg output:
[dmesg.txt](https://github.com/ektor5/secocec/files/2458181/dmesg.txt)

Thanks!

**Comment by ektor5** [comment]
Hi there,

> RIP: 0010:ir_lirc_scancode_event+0x3d/0xb0 [rc_core]

Yes, it is an issue not related to the seco-cec module, but the Linux RC (rc_core) module. It should be fixed now.
Try again with a 4.19-rc* and let me know.

Thanks,
Ettore

**Comment by ocurero** [comment]
Ciao Ettore,

Thanks, using rc9 solved the crash. However, i have another problem later on when I press any button in the remote. It seems like if all buttons were mapped to the same code:

```
ixia:~ # ir-keytable -tv
Found device /sys/class/rc/rc2/
Found device /sys/class/rc/rc0/
Parsing uevent /sys/class/rc/rc0/lirc0/uevent
/sys/class/rc/rc0/lirc0/uevent uevent MAJOR=243
/sys/class/rc/rc0/lirc0/uevent uevent MINOR=0
/sys/class/rc/rc0/lirc0/uevent uevent DEVNAME=lirc0
Input sysfs node is /sys/class/rc/rc0/input4/
Event sysfs node is /sys/class/rc/rc0/input4/event4/
Parsing uevent /sys/class/rc/rc0/input4/event4/uevent
/sys/class/rc/rc0/input4/event4/uevent uevent MAJOR=13
/sys/class/rc/rc0/input4/event4/uevent uevent MINOR=68
/sys/class/rc/rc0/input4/event4/uevent uevent DEVNAME=input/event4
Parsing uevent /sys/class/rc/rc0/uevent
/sys/class/rc/rc0/uevent uevent NAME=rc-hauppauge
/sys/class/rc/rc0/uevent uevent DRV_NAME=secocec
/sys/class/rc/rc0/uevent uevent DEV_NAME=IrDA RC for CEC00001:00
input device is /dev/input/event4
/sys/class/rc/rc0/protocols protocol rc-5 (enabled)
Opening /dev/input/event4
Input Protocol version: 0x00010001
Testing events. Please, press CTRL-C to abort.
1840.857941: lirc protocol(rc5): scancode = 0x0
1840.857994: event type EV_MSC(0x04): scancode = 0x00
1840.857994: event type EV_KEY(0x01) key_down: KEY_0(0x000b)
1840.857994: event type EV_SYN(0x00).
1841.075704: event type EV_KEY(0x01) key_up: KEY_0(0x000b)
1841.075704: event type EV_SYN(0x00).
1958.013911: lirc protocol(rc5): scancode = 0x0
1958.013957: event type EV_MSC(0x04): scancode = 0x00
1958.013957: event type EV_KEY(0x01) key_down: KEY_0(0x000b)
1958.013957: event type EV_SYN(0x00).
1958.085240: lirc protocol(rc5): scancode = 0x0
1958.085302: event type EV_MSC(0x04): scancode = 0x00
1958.085302: event type EV_SYN(0x00).
1958.303852: event type EV_KEY(0x01) key_up: KEY_0(0x000b)
1958.303852: event type EV_SYN(0x00).
1976.466039: lirc protocol(rc5): scancode = 0x0
1976.466102: event type EV_MSC(0x04): scancode = 0x00
1976.466102: event type EV_KEY(0x01) key_down: KEY_0(0x000b)
1976.466102: event type EV_SYN(0x00).
1976.683483: event type EV_KEY(0x01) key_up: KEY_0(0x000b)
1976.683483: event type EV_SYN(0x00).
1981.041971: lirc protocol(rc5): scancode = 0x0
1981.042038: event type EV_MSC(0x04): scancode = 0x00
1981.042038: event type EV_KEY(0x01) key_down: KEY_0(0x000b)
1981.042038: event type EV_SYN(0x00).
1981.259492: event type EV_KEY(0x01) key_up: KEY_0(0x000b)
1981.259492: event type EV_SYN(0x00).

```

How can I assign a different code?

Thanks!

**Comment by ektor5** [comment]
Hi again Oscar,
Thanks a lot for the feedback,

Mh, strange. It doesn't seem to receive a different code.
Can you activate the DEBUG option and post the dmesg?

I actually don't remember the state of the master branch, if you're on the r9 please use the "notifier" branch, it has also cec-notifier support (auto-assigning the physical address and a lot of style fixes).
If you have some issues, please report.

Thanks,
Ettore

**Comment by ocurero** [comment]
Hi,

Mhhh, I tried the "notifier" branch but I have 2 problems now:
- There is not debug output (using master branch works)
- I don't have the ir device:
```

ixia:~ # ir-keytable 
Found /sys/class/rc/rc1/ (/dev/input/event13) with:
        Name: 1-3:1.0 IR
        Driver: em28xx, table: rc-pinnacle-pctv-hd
        lirc device: /dev/lirc1
        Supported protocols: rc-5 nec rc-6 
        Enabled protocols: rc-5 
        bus: 3, vendor/product: 2013:0258, version: 0x0001
        Repeat delay = 500 ms, repeat period = 125 ms

```

However, "cec-ctl -m" does show the correct keys when I press the buttons:

```
ixia:~ # cec-ctl -m  
Driver Info:
        Driver Name                : secocec
        Adapter Name               : CEC00001:00
        Capabilities               : 0x0000000e
                Logical Addresses
                Transmit
                Passthrough
        Driver version             : 4.19.0
        Available Logical Addresses: 1
        Physical Address           : 1.0.0.0
        Logical Address Mask       : 0x0010
        CEC Version                : 2.0
        Vendor ID                  : 0x000c03
        Logical Addresses          : 1 (Allow RC Passthrough)

          Logical Address          : 4 (Playback Device 1)
            Primary Device Type    : Playback
            Logical Address Type   : Playback
            All Device Types       : Playback
            RC TV Profile          : None
            Device Features        :
                None

Initial Event: State Change: PA: 1.0.0.0, LA mask: 0x0010
Received from TV to all (0 to 15): CEC_MSG_DEVICE_VENDOR_ID (0x87):
        vendor-id: 57489 (0x0000e091)
Received from TV to all (0 to 15): CEC_MSG_DEVICE_VENDOR_ID (0x87):
        vendor-id: 57489 (0x0000e091)
Received from TV to all (0 to 15): CEC_MSG_DEVICE_VENDOR_ID (0x87):
        vendor-id: 57489 (0x0000e091)
Received from TV to all (0 to 15): CEC_MSG_DEVICE_VENDOR_ID (0x87):
        vendor-id: 57489 (0x0000e091)
Received from TV to Playback Device 1 (0 to 4): CEC_MSG_POLL
Received from TV to Playback Device 1 (0 to 4): CEC_MSG_USER_CONTROL_PRESSED (0x44):
        ui-cmd: Up (0x01)
Received from TV to Playback Device 1 (0 to 4): CEC_MSG_USER_CONTROL_RELEASED (0x45)
Received from TV to Playback Device 1 (0 to 4): CEC_MSG_USER_CONTROL_PRESSED (0x44):
        ui-cmd: Down (0x02)

```

Thanks!!

**Comment by ektor5** [comment]
Hi Oscar,

On Thu, Oct 18, 2018 at 01:42:42PM -0700, Oscar Curero wrote:
> Hi,
> 
> Mhhh, I tried the "notifier" branch but I have 2 problems now:
> - There is not debug output (using master branch works)

Yes, this is more aligned to what you'll find in the future in the
Linux kernel, if it pass the review.

I should've left them in this repo, I'll make a branch with all the
reverts.

> - I don't have the ir device:
Mh. This is strange. Will investigate tomorrow.

> ```
> 
> ixia:~ # ir-keytable 
> Found /sys/class/rc/rc1/ (/dev/input/event13) with:
>         Name: 1-3:1.0 IR
>         Driver: em28xx, table: rc-pinnacle-pctv-hd
>         lirc device: /dev/lirc1
>         Supported protocols: rc-5 nec rc-6 
>         Enabled protocols: rc-5 
>         bus: 3, vendor/product: 2013:0258, version: 0x0001
>         Repeat delay = 500 ms, repeat period = 125 ms
> 
> ```
> 
> However, "cec-ctl -m" does show the correct keys when I press the buttons:
> 
> ```
> ixia:~ # cec-ctl -m  
> Driver Info:
>         Driver Name                : secocec
>         Adapter Name               : CEC00001:00
>         Capabilities               : 0x0000000e
>                 Logical Addresses
>                 Transmit
>                 Passthrough
>         Driver version             : 4.19.0
>         Available Logical Addresses: 1
>         Physical Address           : 1.0.0.0
>         Logical Address Mask       : 0x0010
>         CEC Version                : 2.0
>         Vendor ID                  : 0x000c03
>         Logical Addresses          : 1 (Allow RC Passthrough)
> 
>           Logical Address          : 4 (Playback Device 1)
>             Primary Device Type    : Playback
>             Logical Address Type   : Playback
>             All Device Types       : Playback
>             RC TV Profile          : None
>             Device Features        :
>                 None
> 
> Initial Event: State Change: PA: 1.0.0.0, LA mask: 0x0010
> Received from TV to all (0 to 15): CEC_MSG_DEVICE_VENDOR_ID (0x87):
>         vendor-id: 57489 (0x0000e091)
> Received from TV to all (0 to 15): CEC_MSG_DEVICE_VENDOR_ID (0x87):
>         vendor-id: 57489 (0x0000e091)
> Received from TV to all (0 to 15): CEC_MSG_DEVICE_VENDOR_ID (0x87):
>         vendor-id: 57489 (0x0000e091)
> Received from TV to all (0 to 15): CEC_MSG_DEVICE_VENDOR_ID (0x87):
>         vendor-id: 57489 (0x0000e091)
> Received from TV to Playback Device 1 (0 to 4): CEC_MSG_POLL
> Received from TV to Playback Device 1 (0 to 4): CEC_MSG_USER_CONTROL_PRESSED (0x44):
>         ui-cmd: Up (0x01)
> Received from TV to Playback Device 1 (0 to 4): CEC_MSG_USER_CONTROL_RELEASED (0x45)
> Received from TV to Playback Device 1 (0 to 4): CEC_MSG_USER_CONTROL_PRESSED (0x44):
>         ui-cmd: Down (0x02)
> 
> ```

Thanks again for the feedback,
	Ettore

**Comment by ocurero** [comment]
Hi Ettore,

I tried your last patch but, although the device is now created, I have the same problem as before, the buttons are not detected.

If you think is better to try your patches that you are posting to the lkml, I can test them as well.

Thanks for your work!!

**Comment by ocurero** [comment]
Do you have any update?

Thanks!

**Comment by ocurero** [comment]
No update?

**Comment by ektor5** [comment]
Hi @ocurero,
The driver should work, I didn't have any problem with it, so I assume that there is something wrong with your settings. Be sure to have the last firmware installed. Please try sending me more debug outputs and try using an Ubuntu 18.04 as reference.

However, I invite you to try the driver shipped in the Linux Kernel 5.0, I've also fixed a bug on IR.

Regards,
Ettore

**Comment by ektor5** [comment]
I've done some merging and a commit closed the issue, was not intentional :)
Let me know,
Ettore

**Comment by ocurero** [comment]
Hi!

I tried kernel 5.0-rc7, but that didn't help. The UEFI firmware is at 1.04 (not the latest one, but in theory it has all the changes related to CEC).

Out of 30 times, only twice the buttons are recognized by ir-keymap and always with the same code, which is very strange. Yep, it must be a settings issue (afterall, cec-ctl works fine and all buttons are recognized without problems). But I can't see any setting to modify.

Although ir-keytable finds 2 rc devices, at boot there are 3:
[    8.783466] rc rc0: lirc_dev: driver PicoLCD (graphic) registered at minor = 0, raw IR receiver, no transmitter
[   11.011770] rc rc1: lirc_dev: driver secocec registered at minor = 1, scancode receiver, no transmitter
[   13.354424] rc rc2: lirc_dev: driver em28xx registered at minor = 2, scancode receiver, no transmitter

Notice that the first one (rc0) doesn't show up:

Found /sys/class/rc/rc1/ (/dev/input/event5) with:
        Name: CEC00001:00
        Driver: secocec, table: rc-hauppauge
        lirc device: /dev/lirc1
        Supported protocols: rc-5 
        Enabled protocols: rc-5 
        bus: 25, vendor/product: 0000:0000, version: 0x0001
        Repeat delay = 500 ms, repeat period = 125 ms
Found /sys/class/rc/rc2/ (/dev/input/event14) with:
        Name: 1-3:1.0 IR
        Driver: em28xx, table: rc-pinnacle-pctv-hd
        lirc device: /dev/lirc2
        Supported protocols: rc-5 nec rc-6 
        Enabled protocols: rc-5 
        bus: 3, vendor/product: 2013:0258, version: 0x0001
        Repeat delay = 500 ms, repeat period = 125 ms

What kind of debugging would you like? Do i need to compile the secocec module with the debug flag or can it be enabled at boot?

Thanks again!

**Comment by ektor5** [comment]
Hi Oscar, 
You have to update to the latest version of the Bios.
Actually the old Bios can lead to malfunctioning and random behavior,
the latest driver work only with >=1.06. 

Best Regards, 
Ettore

**Comment by ektor5** [comment]
Hi @ocurero,
Hope everything is going well, I'm closing this issue.
