### ISSUE TITLE
Random scancode

### ISSUE THREAD

**Issue by ocurero** [ektor5/secocec#5]
Hi,

For the same rc button, every time I push it, it generates a new scancode:

ixia:/etc/modprobe.d # ir-keytable -tv
Found device /sys/class/rc/rc0/
Parsing uevent /sys/class/rc/rc0/lirc0/uevent
/sys/class/rc/rc0/lirc0/uevent uevent MAJOR=244
/sys/class/rc/rc0/lirc0/uevent uevent MINOR=0
/sys/class/rc/rc0/lirc0/uevent uevent DEVNAME=lirc0
Input sysfs node is /sys/class/rc/rc0/input6/
Event sysfs node is /sys/class/rc/rc0/input6/event6/
Parsing uevent /sys/class/rc/rc0/input6/event6/uevent
/sys/class/rc/rc0/input6/event6/uevent uevent MAJOR=13
/sys/class/rc/rc0/input6/event6/uevent uevent MINOR=70
/sys/class/rc/rc0/input6/event6/uevent uevent DEVNAME=input/event6
Parsing uevent /sys/class/rc/rc0/uevent
/sys/class/rc/rc0/uevent uevent NAME=rc-hauppauge
/sys/class/rc/rc0/uevent uevent DRV_NAME=secocec
/sys/class/rc/rc0/uevent uevent DEV_NAME=CEC00001:00
input device is /dev/input/event6
/sys/class/rc/rc0/protocols protocol rc-5 (enabled)
Opening /dev/input/event6
Input Protocol version: 0x00010001
Testing events. Please, press CTRL-C to abort.
2571.718745: lirc protocol(rc5): scancode = 0x1e7f
2571.718815: event type EV_MSC(0x04): scancode = 0x1e7f
2571.718815: event type EV_SYN(0x00).
2574.631452: lirc protocol(rc5): scancode = 0x2c6d toggle=1
2574.631499: event type EV_MSC(0x04): scancode = 0x2c6d
2574.631499: event type EV_SYN(0x00).
2574.993309: lirc protocol(rc5): scancode = 0x243f
2574.993367: event type EV_MSC(0x04): scancode = 0x243f
2574.993367: event type EV_SYN(0x00).
2575.017509: lirc protocol(rc5): scancode = 0x2c6d toggle=1
2575.017576: event type EV_MSC(0x04): scancode = 0x2c6d
2575.017576: event type EV_SYN(0x00).
2575.356507: lirc protocol(rc5): scancode = 0x3a1b
2575.356570: event type EV_MSC(0x04): scancode = 0x3a1b
2575.356570: event type EV_SYN(0x00).
2575.783898: lirc protocol(rc5): scancode = 0x2c6d toggle=1
2575.783944: event type EV_MSC(0x04): scancode = 0x2c6d
2575.783944: event type EV_SYN(0x00).
2576.553955: lirc protocol(rc5): scancode = 0x1c2d
2576.554011: event type EV_MSC(0x04): scancode = 0x1c2d
2576.554011: event type EV_SYN(0x00).
2579.459767: lirc protocol(rc5): scancode = 0x3e3f toggle=1
2579.459837: event type EV_MSC(0x04): scancode = 0x3e3f
2579.459837: event type EV_KEY(0x01) key_down: KEY_OK(0x0160)
2579.459837: event type EV_SYN(0x00).
2579.676319: event type EV_KEY(0x01) key_up: KEY_OK(0x0160)
2579.676319: event type EV_SYN(0x00).

Thanks,

**Comment by ektor5** [comment]
Hi Oscar,  
Please remind that UDOO X86 can decode only RC5 IR codes.  

Seems like your remote isn't RC5 compliant.  

Best Regards,  
Ettore

EDIT: Please make sure to use BIOS 1.06 when using the latest driver version
