### ISSUE TITLE
Device probe failed

### ISSUE THREAD

**Issue by trs79** [ektor5/secocec#6]
I have succesfully compiled the kernel module and am using bios 1.06. On boot, I see the following in dmesg:

```
secocec CEC00001:00: Cannot request interrupt gpio
secocec CEC00001:00: Cannot assign gpio to IRQ
secocec CEC00001:00: CEC00001:00 device probe failed
```

There isn't any cec device created. Is there anything else I could try? Thanks.

**Comment by stowellt** [comment]
It turns out I had to load the pinctrl-cherryview kernel module first, then the seco driver loaded correctly.

**Comment by trs79** [comment]
It turns out I had to load the pinctrl-cherryview kernel module first, then the seco driver loaded correctly.
