### ISSUE TITLE
/dev/cec0 does not exist, "secocec CEC00001:00: Request memory region failed" error at boot

### ISSUE THREAD

**Issue by fedus** [ektor5/secocec#8]
Hello,

I have a Udoo x86 (first version), running Ubuntu 20.04.2 LTS (5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)

I realised CEC doesn't work anymore. Running `cec-ctl` says that `/dev/cec0` doesn't exist, and `dmesg | grep -i cec` returns "secocec CEC00001:00: Request memory region failed".

At the same time:
```
➜  ~ cat /proc/modules | grep cec                      
seco_cec 24576 0 - Live 0x0000000000000000
rc_core 53248 1 seco_cec, Live 0x0000000000000000
```

The board is on the latest firmware (1.06).

My expectation was that with the Kernel I'm using (combined with latest firmware), it would just work out of the box.

I have used CEC successfully on this very board with the same tv and same cable, but on earlier Ubuntu versions (and by compiling and loading the driver from this repo manually).

Is there anything I could do to try to get it back up and running again?

Thanks!

**Comment by i81b4u** [comment]
As stated on the main page, blacklisting i2c-i801 solved the exact problem you described.

echo "blacklist i2c-i801" > /etc/modprobe.d/i2c-i801.conf

**Comment by ektor5** [comment]
Thanks @i81b4u,
Unfortunately at the state of the art is not possible to use i2c-i801 directly to access SMBus from the subsystem, due to a conflict with ACPI.
A patch is in the works and it could be possible to use this method in the future.

Ettore
