### ISSUE TITLE
Possible to use other protocols besides RC5?

### ISSUE THREAD

**Issue by stowellt** [ektor5/secocec#9]
Is it possible to decode other IR protocols besides RC5? I noticed the receiver module seems to support multiple protocols: https://www.newark.com/vishay/tsop75238tr/infrared-receiver-remote-control/dp/48W3590

**Comment by ektor5** [comment]
Hi @stowellt,
Unfortunately the decoding is done in the Embedded Controller, so it is fixed to decode only RC-5.
Once an RC-5 is decoded, the message is signaled and made it available from the driver to be read.

Regards,
Ettore
